version: '3.9'

services:
  message_broker:
    image: redis:latest
    ports:
      - "6380:6379"

  chamazetu_pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      - DB_USER=${SUPABASE_DB_USER}
      - DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - DB_HOST=${SUPABASE_DB_HOST}
      - AUTH_TYPE=md5
      - POOL_MODE=transaction
      - LISTEN_PORT=6432
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt

  chamazetu_frontend:
    image: ghcr.io/mankindjnr/chamazetu_frontend:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker
    deploy:
      replicas: 2

  chamazetu_backend:
    image: ghcr.io/mankindjnr/chamazetu_backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --reload
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@chamazetu_pgbouncer:6432/${SUPABASE_DB_NAME}
    depends_on:
      - chamazetu_pgbouncer
    deploy:
      replicas: 4

  celery_worker:
    image: ghcr.io/mankindjnr/celery_worker:latest
    command: celery -A frontend_chamazetu.celery worker -l INFO
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker
    deploy:
      replicas: 3

  celery_beat_scheduler:
    image: ghcr.io/mankindjnr/celery_beat_scheduler:latest
    command: celery -A frontend_chamazetu.celery beat -l INFO
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chamazetu_frontend
      - chamazetu_backend
