services:
  message_broker:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - chamazetu_network

  chamazetu_prod_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    volumes:
      - chamazetu_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chamazetu_network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=chamazetu_prod_db
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - LISTEN_PORT=6432
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - chamazetu_network

  chamazetu_frontend:
    image: ghcr.io/mankindjnr/chamazetu_frontend:latest
    command: >
      sh -c "python manage.py collectstatic --no-input && gunicorn frontend_chamazetu.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - TZ=Africa/Nairobi
    depends_on:
      - message_broker
    networks:
      - chamazetu_network
    deploy:
      replicas: 2

  chamazetu_backend:
    image: ghcr.io/mankindjnr/chamazetu_backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --workers 4
    environment:
      - TZ=Africa/Nairobi
    depends_on:
      - pgbouncer
    networks:
      - chamazetu_network
    deploy:
      replicas: 4

  celery_worker:
    image: ghcr.io/mankindjnr/celery_worker:latest
    command: celery -A frontend_chamazetu.celery worker -l INFO
    environment:
      - TZ=Africa/Nairobi
      - C_FORCE_ROOT=true
    depends_on:
      - message_broker
    networks:
      - chamazetu_network
    deploy:
      replicas: 3

  celery_beat_scheduler:
    image: ghcr.io/mankindjnr/celery_beat_scheduler:latest
    command: celery -A frontend_chamazetu.celery beat -l INFO
    environment:
      - TZ=Africa/Nairobi
    depends_on:
      - message_broker
    networks:
      - chamazetu_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chamazetu_frontend
      - chamazetu_backend
    networks:
      - chamazetu_network

volumes:
  chamazetu_data:


networks:
  chamazetu_network:
    driver: bridge
