version: '3.9'

services:
  message_broker:
    image: redis:latest
    ports:
      - "6380:6379"

  chamazetu_frontend:
    image: ghcr.io/mankindjnr/chamazetu_frontend:latest
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker
    deploy:
      replicas: 2

  chamazetu_backend:
    image: ghcr.io/mankindjnr/chamazetu_backend:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --reload
    environment:
      - DATABASE_URL=postgres://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@{SUPABASE_DB_HOST}:5432/${SUPABASE_DB_NAME}
    depends_on:
      - message_broker
    deploy:
      replicas: 4

  celery_worker:
    image: ghcr.io/mankindjnr/celery_worker:latest
    command: celery -A frontend_chamazetu.celery worker --pool=solo -l INFO
    environment:
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker
    deploy:
      replicas: 2

  celery_beat_scheduler:
    image: ghcr.io/mankindjnr/celery_beat_scheduler:latest
    command: celery -A frontend_chamazetu.celery beat -l INFO
    environment:
      - DATABASE_URL=postgres://${SUPA_DB_USER}:${SUPA_DB_PASSWORD}@${SUPA_DB_HOST}:5432/${SUPA_DB_NAME}
    depends_on:
      - message_broker

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chamazetu_frontend
      - chamazetu_backend
