services:
  chamazetu_database:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth=scram-sha-256
    volumes:
      - chamazetu_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - chamazetu_network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=chamazetu_database
      - AUTH_TYPE=scram-sha-256
      - POOL_MODE=transaction
      - LISTEN_PORT=6432
    ports:
      - "6432:6432"
    depends_on:
      - chamazetu_database
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    networks:
      - chamazetu_network

  message_broker:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - chamazetu_network

  backend_message_broker:
    image: redis:latest
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    environment:
      - TZ=Africa/Nairobi
    networks:
      - chamazetu_network

  chamazetu_frontend_database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${FRONTEND_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FRONTEND_POSTGRES_PASSWORD}
      POSTGRES_DB: ${FRONTEND_POSTGRES_DB}
    volumes:
      - frontend_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - chamazetu_network

  chamazetu_backend_celery_database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${BACKEND_CELERY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BACKEND_CELERY_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BACKEND_CELERY_POSTGRES_DB}
    volumes:
      -  backend_celery_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - chamazetu_network

  chamazetu_frontend:
    image: ghcr.io/mankindjnr/chamazetu_frontend:latest
    restart: always
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --no-input && gunicorn frontend_chamazetu.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    environment:
      - TZ=Africa/Nairobi
    depends_on:
      - chamazetu_frontend_database
      - message_broker
    networks:
      - chamazetu_network
    deploy:
      replicas: 3

  chamazetu_backend:
    image: ghcr.io/mankindjnr/chamazetu_backend:latest
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 9400 --workers 4
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@pgbouncer:6432/${DB_NAME}
    depends_on:
      - chamazetu_database
      - message_broker
      - pgbouncer
    networks:
      - chamazetu_network
    deploy:
      replicas: 3

  celery_worker:
    image: ghcr.io/mankindjnr/celery_worker:latest
    restart: always
    command: celery -A frontend_chamazetu.celery worker -l INFO
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${FRONTEND_POSTGRES_USER}:${FRONTEND_POSTGRES_PASSWORD}@chamazetu_frontend_database:5432/${FRONTEND_POSTGRES_DB}
      - C_FORCE_ROOT=true
    depends_on:
      - message_broker
    networks:
      - chamazetu_network
    deploy:
      replicas: 3

  celery_backend_worker:
    image: ghcr.io/mankindjnr/celery_backend_worker:latest
    restart: always
    command: celery -A app.celery worker --pool=solo -l INFO
    environment:
      - TZ=Africa/Nairobi
      - DATABASE_URL=postgres://${BACKEND_CELERY_POSTGRES_USER}:${BACKEND_CELERY_POSTGRES_PASSWORD}@chamazetu_backend_celery_database:5432/${BACKEND_CELERY_POSTGRES_DB}
      - C_FORCE_ROOT=true
    depends_on:
      - chamazetu_backend_celery_database
      - backend_message_broker
    networks:
      - chamazetu_network
    deploy:
      replicas: 3

  celery_beat_scheduler:
    image: ghcr.io/mankindjnr/celery_beat_scheduler:latest
    restart: always
    command: celery -A frontend_chamazetu.celery beat -l INFO
    environment:
      - DATABASE_URL=postgres://${FRONTEND_POSTGRES_USER}:${FRONTEND_POSTGRES_PASSWORD}@chamazetu_frontend_database:5432/${FRONTEND_POSTGRES_DB}
      - TZ=Africa/Nairobi
    depends_on:
      - message_broker
    networks:
      - chamazetu_network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - chamazetu_frontend
      - chamazetu_backend
    networks:
      - chamazetu_network

volumes:
  redis_data:
  chamazetu_data:
  frontend_data:
  backend_celery_data:


networks:
  chamazetu_network:
    driver: bridge
